version: 2.0
workflows:
  version: 2
  build:
    jobs:
      - language=c
      - language=go
jobs:
  language=c:
    description: build test case written in C
    docker:
      - image: debian:latest
    working_directory: /src
    steps:
    - checkout
    - setup_remote_docker
    - run:
        command: docker build -t zrepl_build -f copyfilerange.c.Dockerfile .

  language=go:
    description: build test case written in Go
    docker:
      - image: debian:latest
    working_directory: /src
    steps:
    - checkout
    - setup_remote_docker
    - run:
        command: docker build -t zrepl_build -f copyfilerange.go.Dockerfile .

